# BasicCAD

We are creating a caster.

---
## Table of Contents
* [Table of Contents](#Table-of-Contents)
* [Base](#Base)
* [Mount](#Mount)
* [Fork](#Fork)
* [Tire](#Tire)
* [Wheel](#Wheel)
* [AxleCollarBearings](#AxleCollarBearings)
* [SubAssembly](#SubAssembly)

## Base

### Description

The first assignment is to create the caster base. It is a rectangle with 6 holes equally spaced and one bigger hole between 4 of the holes.

### Evidence

https://cvilleschools.onshape.com/documents/fc3a9d06629276e022e9e563/w/c57c371bcaf7ec4a64d9e043/e/1491b92841ee2fa70b5db4dd

### Image

![Image of Base](https://github.com/Olindsa32/BasicCAD/blob/master/CasterProject/Images/CasterBase.png?raw=true)

### Reflection

This assignment provided no problem. The assignment talked about doing a linear pattern after creating one circle and that works well. I did the one going 3 wide first and just spaced them manually by 80. Then I did the one by 2 to flip it to the other side. That was the most difficult part of the assignment.
 
---


## Mount

### Description

The mount is a piece that goes on top of the base and matches up with the holes from one side of the base. It is a perfect square centered around the large hole from the base.

### Evidence

https://cvilleschools.onshape.com/documents/fc3a9d06629276e022e9e563/w/c57c371bcaf7ec4a64d9e043/e/1491b92841ee2fa70b5db4dd

### Image

![Image of Mount](https://github.com/Olindsa32/BasicCAD/blob/master/CasterProject/Images/CasterMount.png?raw=true)

### Reflection

This one was just as easy as the base maybe easier. Instead of doing a linear sketch pattern like I did on the base since it was a square I could instead do a circular sketch pattern which only took putting 4 on the amount and choosing the center of the square for the rotation point.

---


## Fork

### Description

The fork is a disk with an 80 mm diameter. On one side of it is a 20 mm diameter cylinder that is 65 mm long. That side of the fork goes through the large hole from the mount and the base. The other side has an extrusion mirrored over the center line 75 mm tall with fillets. They are 30 mm apart. They have matching holes so that the wheel can sit in the middle and be supported by a rod going through both of the holes. 

### Evidence

https://cvilleschools.onshape.com/documents/fc3a9d06629276e022e9e563/w/c57c371bcaf7ec4a64d9e043/e/1491b92841ee2fa70b5db4dd

### Image

![Image of Fork](https://github.com/Olindsa32/BasicCAD/blob/master/CasterProject/Images/CasterFork.png?raw=true)

### Reflection

On this assignment one important thing to do is to space the extrusions correctly. The picture is misleading and it looks like it wants you to give it 15 mm from the center line to the center of the rectangle. What it actually wants you to do is go from the center line to the closest edge of the rectangle. You knw you did this wrong if the wheel is overlapping with the fork after mating them in your assembly.

---


## Tire

### Description

The tire is just a black circle with a huge hole in the middle. It also has 2 fillets on the edge to make it look like a tire. The diameter is 110 mm

### Evidence

https://cvilleschools.onshape.com/documents/fc3a9d06629276e022e9e563/w/c57c371bcaf7ec4a64d9e043/e/1491b92841ee2fa70b5db4dd

### Image

![Image of Tire](https://github.com/Olindsa32/BasicCAD/blob/master/CasterProject/Images/CasterTire.png?raw=true)


### Reflection

The creation of this assignment is unique because instead of creating a circle then extruding it you instead create a trapezoid as a sketch, space it from a construction line and revolve the trapezoid around the construction line to create a circle and keep the trapezoid shape.

---


## Wheel

### Description

The wheel shape is essentially like a capital I that is then revolved to make it a circle. After that you create angled lines to make the 5 cuts to have it resemble a wheel.

### Evidence

https://cvilleschools.onshape.com/documents/fc3a9d06629276e022e9e563/w/c57c371bcaf7ec4a64d9e043/e/1491b92841ee2fa70b5db4dd

### Image

![Image of Wheel](https://github.com/Olindsa32/BasicCAD/blob/master/CasterProject/Images/CasterWheel.png?raw=true)

### Reflection

The hardest part of this assignment is creating the cuts in the wheel. You have to create 2 lines 60 degrees apart. After you have that shape you make two circles from the center of the wheel so that you end up with the shape that you want for the cuts. Then you have to make the circular sketch pattern so you don't have just one cut.

---


## AxleCollarBearings

### Description

This assingment did not provide much of an issue because it was just 3 simple pieces that later needed to be mated together instead of a big complex piece

### Evidence

https://cvilleschools.onshape.com/documents/fc3a9d06629276e022e9e563/w/c57c371bcaf7ec4a64d9e043/e/1491b92841ee2fa70b5db4dd

### Image

![Image of Axle and Collar](https://github.com/Olindsa32/BasicCAD/blob/master/CasterProject/Images/CasterAxleCollar.png?raw=true)
![Image of Bearing](https://github.com/Olindsa32/BasicCAD/blob/master/CasterProject/Images/CasterBearing.png?raw=true)

### Reflection

This assignment was mostly just making a cylinder and putting another cylinder on top of it. but the one potentially hard part wouuld be when you create the second piece you have to put the sketch on the end and then reverse the direction so that it will extrude back towards the previous sketch.

---


## SubAssmebly

### Description

This assignment includes putting the wheel inside the tire and adding bearings to the side to prepare the entire wheel for the full assembly. Once you create this subassmebly it will be very easy to stick this shape between the 2 fork sides.

### Evidence

https://cvilleschools.onshape.com/documents/fc3a9d06629276e022e9e563/w/c57c371bcaf7ec4a64d9e043/e/1491b92841ee2fa70b5db4dd

### Image

![Image of SubAssembly](https://github.com/Olindsa32/BasicCAD/blob/master/CasterProject/Images/CasterSubAssembly.png?raw=true)

### Reflection

In onshape to do mates it is much easier than it was in solidworks, you do not need to mate three different edges of something to get it fully in place you simply need to choose the correct type of mate and select the spot where things go to together. Putting together the wheel and tire you can press anywhere on the outside of the wheel and the inside of the tire. To add the bearing you want to grab the correct side and press in the middle of it and do the same with the wheel.
